#!/usr/bin/env python3
"""
Collect Windows (5a44765) + Linux (current run) JSON into evidence table.
Run inside eval container after pytest; writes tests/results/linux/REPORT.md
Measure-only — never fails the run.
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
WIN_DIR = ROOT / "tests" / "results"
LINUX_DIR = ROOT / "tests" / "results" / "linux"

# Map metric -> (windows_file, linux_file, extractor)
def read_json(p: Path):
    try:
        return json.loads(p.read_text(encoding="utf-8"))
    except Exception:
        return None

win_lat = read_json(WIN_DIR / "latency.json") or {}
linux_lat = read_json(LINUX_DIR / "latency.json") or {}
win_warm = read_json(WIN_DIR / "startup_warm.json") or {}
linux_warm = read_json(LINUX_DIR / "startup_warm.json") or {}
win_cold = read_json(WIN_DIR / "startup_cold.json") or {}
linux_cold = read_json(LINUX_DIR / "startup_cold.json") or {}

# cgroup probe via direct FS read (Linux only)
cgroup_mode = "unknown"
pids_max = "unknown"
pids_current = "unknown"
try:
    if Path("/sys/fs/cgroup/cgroup.controllers").exists():
        cgroup_mode = "v2"
        controllers = Path("/sys/fs/cgroup/cgroup.controllers").read_text().strip()
        cgroup_mode = f"v2 ({controllers})" if controllers else "v2"
    elif Path("/sys/fs/cgroup/memory").exists():
        cgroup_mode = "v1"
    else:
        cgroup_mode = "none"
except Exception as e:
    cgroup_mode = f"error: {e}"

try:
    # pids controller is at /sys/fs/cgroup/pids.max on v1, or /sys/fs/cgroup/pids.max on v2 unified? Actually v2: /sys/fs/cgroup/pids.max or /sys/fs/cgroup/<cgroup>/pids.max
    for cand in [Path("/sys/fs/cgroup/pids.max"), Path("/sys/fs/cgroup/pids.current")]:
        if cand.exists():
            pids_max = cand.with_name("pids.max").read_text().strip() if cand.name == "pids.current" else cand.read_text().strip()
            break
    cur = Path("/sys/fs/cgroup/pids.current")
    if cur.exists():
        pids_current = cur.read_text().strip()
except Exception:
    pass

report = f"""# Phase 7-full — Linux Evidence (vs Windows 5a44765)

**Date:** auto-generated by `tests/docker/collect.py`
**Windows baseline:** `5a44765` `tests/results/REPORT.md` (304ms/87ms etc.)
**Linux:** current `tests/results/linux/*.json`
**Mode:** measure-only

| Metric                  | Windows/TestClient | Linux/Docker |
| ----------------------- | -----------------: | -----------: |
| Exec latency            | {win_lat.get('nallputer_ms','—')} ms | {linux_lat.get('nallputer_ms','⏳')} ms |
| Local baseline          | {win_lat.get('baseline_subprocess_ms','—')} ms | {linux_lat.get('baseline_subprocess_ms','⏳')} ms |
| Overhead                | {win_lat.get('overhead_x','—')}× | {linux_lat.get('overhead_x','⏳')}× |
| Warm startup            | {win_warm.get('warm_ms','—')} ms | {linux_warm.get('warm_ms','⏳')} ms |
| Cold startup            | {win_cold.get('cold_ms','—')} ms* | {linux_cold.get('cold_ms','⏳')} ms |
| cgroup v2 enforcement   | N/A | {cgroup_mode} |
| `pids.max`              | N/A | {pids_max} |
| `pids.current`          | N/A | {pids_current} |
| 5-way concurrency       | ⏳ | ⏳ (run `pytest -k concurrency` inside container) |
| Process-group kill      | Windows `taskkill` | Linux `setsid`/`killpg` |
| Environment replay      | partial | ⏳ |
| Private-network latency | ⏳ | ⏳ |

* Windows cold is import-only, not Render container boot.

**Files:**
- Windows: `tests/results/*.json`
- Linux: `tests/results/linux/*.json` (+ `junit.xml`, `pytest.log`)

**Verdict placeholder:** fill after first real `make eval-linux` run.
"""

LINUX_DIR.mkdir(parents=True, exist_ok=True)
out = LINUX_DIR / "REPORT.md"
out.write_text(report, encoding="utf-8")
print(f"Wrote {out}")
print(report)
